# Change these first
owner: jfinstrom # Your GitHub username
repo: apistatus # Your GitHub repository name

# Add your sites here
sites:
  - name: CIP Mirror
    method: POST
    url: https://mirror.clearlyip.com/all-15.0.xml
  - name: FreePBX Mirror HTTP Endpoint
    method: POST
    url: http://mirror.freepbx.org/all-15.0.xml
  - name: FreePBX Mirror HTTPS Endpoint
    method: POST
    url: https://mirror.freepbx.org/all-15.0.xml
  - name: Personal Page
    url: https://g3p0.xyz
  - name: TCP ping
    url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: apistatus.site
  theme: dark
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: APISTATUS
  introTitle: "James' uptime thingy..."
  introMessage: This is a page for me to watch things. It is a personal project and not affiliated with the things it is watching. 
  navbar:
    - title: Status
      href: /      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
